parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - group: BUILD Management Resources
  workspace:
    clean: all
  steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 10.0.x
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      RunAcceptanceTests: false
      SonarCloudProjectKey: SkillsFundingAgency_das-tools-support-jobs
  - task: DotNetCoreCLI@2
    displayName: Publish Function App
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.csproj
      arguments: -o $(Build.ArtifactStagingDirectory)/publish/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }} -c ${{ parameters.BuildConfiguration }} --no-build
      modifyOutputPath: false
      zipAfterPublish: true
  - task: CopyFiles@2
    inputs:
      Contents: azure/**
      TargetFolder: $(Build.ArtifactStagingDirectory)/publish
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
