parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  workspace:
    clean: all
  steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 10.0.x
  - task: DotNetCoreCLI@2
    displayName: Build and run unit tests
    inputs:
      command: test
      projects: src/${{ parameters.SolutionBaseName }}.sln
      arguments: --configuration ${{ parameters.BuildConfiguration }} --collect:"XPlat Code Coverage"
  - task: DotNetCoreCLI@2
    displayName: Publish Function App
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.csproj
      arguments: --configuration ${{ parameters.BuildConfiguration }} --no-build --output $(Build.ArtifactStagingDirectory)/publish
      modifyOutputPath: true
      zipAfterPublish: true
  - task: CopyFiles@2
    inputs:
      Contents: azure/**
      TargetFolder: $(Build.ArtifactStagingDirectory)/publish
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
